### ISSUE TITLE
copy-store fails when graph size is greater than Integer.MAXVALUE

### ISSUE THREAD

**Issue by gmann11** [jexp/store-utils#45]
copy-store fails on a large graph where the max id > max integer with:
```
Copying from /x/graph.db to /y/graph.db ingoring rel-types [] ignoring properties [false] ignoring labels [] removing nodes with labels [] keep node ids false 
Exception in thread "main" java.lang.IllegalArgumentException: initial capacity cannot be less than 0
    at org.eclipse.collections.impl.map.mutable.primitive.LongLongHashMap.<init>(LongLongHashMap.java:87)
    at org.neo4j.tool.StoreCopy.copyNodes(StoreCopy.java:219)
    at org.neo4j.tool.StoreCopy.copyStore(StoreCopy.java:82)
    at org.neo4j.tool.StoreCopy.main(StoreCopy.java:49)
```

It looks like there is a cast from long to int on StoreCopy.java:219 causing the issue.

**Comment by jexp** [comment]
@gmann11 where do you see this cast? Can't see it? There is only one cast to int for a percentage output.

Which version are you looking at?

**Comment by jexp** [comment]
Ah found it here in the 3.5 branch:

https://github.com/jexp/store-utils/blob/3.5/src/main/java/org/neo4j/tool/StoreCopy.java#L219

**Comment by jexp** [comment]
I pushed a fix to the 3.5 branch, could you try to build and use that?

**Comment by jexp** [comment]
Or us this: https://www.dropbox.com/s/76knvxrnynb0c5q/store-util-3.5.1-release.zip?dl=0
