### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by bobyin** [jexp/store-utils#62]
Hi

Could you please have a look for my issue?

```
bobyin@~/Desktop/store-util-3.5.23$./copy-store.sh community ~/Desktop/neo4j-community-3.5.30/data/databases/graph.db ./fixed.db
To use your existing Neo4j 3.5.x installation set NEO4J_HOME to your Neo4j directory. Currently set to: /Users/bobyin/Desktop/neo4j-community-3.5.30/data/databases/graph.db
Usage: copy-store.sh [community|enterprise] source.db target.db [RELS,TO,SKIP] [props,to,skip] [Labels,To,Skip] [Labels,To,Delete,Nodes]

Using: Heap 4G Pagecache 2G Edition 'community' from '/Users/bobyin/Desktop/neo4j-community-3.5.30/data/databases/graph.db' to './fixed.db' skipping labels: '', removing nodes with labels: '' rels: '' props '' Keeping Node Ids: 

Please note that you will need this memory (2G + 1G + 4G) as it opens 2 databases one for reading and one for writing.

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/collections/api/map/primitive/MutableLongLongMap
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.eclipse.collections.api.map.primitive.MutableLongLongMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

Here is my JAVA version

```
bobyin@~/Desktop/store-util-3.5.23$java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by bobyin** [comment]
It's my fault, sorry
